[package]
name = "czkawka_cli"
version = "1.0.0"
authors = ["Rafał Mikrut <mikrutrafal54@gmail.com>"]
edition = "2018"
description = "CLI frontend of Czkawka"
license = "MIT"
homepage = "https://github.com/qarmin/czkawka"
repository = "https://github.com/qarmin/czkawka"

[dependencies]
czkawka_core = { path = "../czkawka_core" }
structopt = "0.3.18"